---

- name: Lufi | Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: no

- name: Lufi | Install essential packages
  apt: name="{{ item }}" state=present
  loop:
    - build-essential
    - git
    - libssl-dev
    - libpq-dev # required for Mojo::PG (even if PGSQL won't be used)

- name: Lufi | Install essential packages (bionic)
  apt: name=libdata-entropy-perl state=present
  when: ansible_distribution_release == 'bionic'

- name: Lufi | Install cpanm
  get_url:
    url: https://cpanmin.us
    dest: /usr/local/bin/cpanm
    mode: 0555

- name: Lufi | Install Carton
  command: creates=/usr/local/bin/carton cpanm Carton
