---

- name: Lufi | Checkout git repository
  git:
    repo: "{{lufi_git_repo}}"
    dest: "{{ lufi_working_dir }}"
    update: "{{ lufi_keep_updated }}"
    force: yes
  register: lufi_git_updated
  changed_when: lufi_git_updated.changed
  notify: restart lufi

- name: Lufi | Copy config
  template:
    src: lufi.conf.j2
    dest: "{{ lufi_working_dir }}/lufi.conf"
    mode: 0644
  notify: restart lufi

- name: Lufi | Install lufi
  command: carton install
  args:
    chdir: "{{ lufi_working_dir }}"
    creates: "{{ lufi_db_path }}"
  register: lufi_app_installed
  notify: restart lufi

- name: Lufi | Update lufi
  command: carton update
  args:
    chdir: "{{ lufi_working_dir }}"
  when: lufi_keep_updated
  register: lufi_app_updated
  changed_when: "'Successfully installed' in lufi_app_updated.stdout"
  notify: restart lufi

- name: Lufi | Set ownership on working directory
  file:
    path: "{{ lufi_working_dir }}"
    state: directory
    owner: "{{ lufi_user }}"
    group: "{{ lufi_group }}"
    mode: 0755
    recurse: yes
  changed_when: no

- name: Lufi | Set ownership on files directory
  file:
    path: "{{ lufi_working_dir }}/files"
    state: directory
    owner: "{{ lufi_user }}"
    group: "{{ lufi_group }}"
    mode: 0775
    recurse: yes
  changed_when: no
